---
- name: Create undercloud image
  command: /usr/bin/qemu-img create -f qcow2 {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 {{ UNDERCLOUD_IMAGE_SIZE }}

- name: Expand undercloud image size
  shell: /usr/bin/virt-resize --expand /dev/sda1 {{ RHEL_QCOW }} {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2
  environment:
    LIBGUESTFS_BACKEND: direct

- name: Virt customize undercloud image
  shell: | 
    /usr/bin/virt-customize  -a {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 \
    --run-command 'xfs_growfs /' \
    --root-password password:{{ UNDERCLOUD_ROOT_PWD }} \
    --hostname {{ UNDERCLOUD_NAME }}.local \
    --run-command 'useradd stack' \
    --password stack:password:{{ UNDERCLOUD_STACK_PWD }} \
    --run-command 'echo "stack ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/stack' \
    --chmod 0440:/etc/sudoers.d/stack \
    --run-command 'sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config' \
    --run-command 'systemctl enable sshd' \
    --run-command 'yum remove -y cloud-init' \
    --ssh-inject root:file:{{ ROOT_SSH_KEY }} \
    --ssh-inject stack:file:{{ STACK_SSH_KEY }} \
    --selinux-relabel
  environment:
    LIBGUESTFS_BACKEND: direct

- name: Install undercloud without external api nw
  command: |
    virt-install --name {{ UNDERCLOUD_NAME }} \
    --disk {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 \
    --vcpus={{ UNDERCLOUD_VCPU }} \
    --ram={{ UNDERCLOUD_RAM }} \
    --network network={{ UNDERCLOUD_DEFAULT_NW }},model=virtio \
    --network network={{ UNDERCLOUD_PROV_NW }},model=virtio \
    --network network={{ UNDERCLOUD_INT_API_NW }},model=virtio \
    --virt-type kvm \
    --cpu host \
    --import \
    --os-variant rhel7 \
    --graphics vnc \
    --serial pty \
    --noautoconsole \
    --console pty,target_type=virtio
  when: UNDERCLOUD_EXTERNAL_API_IP is undefined and UNDERCLOUD_MAC is undefined

- name: Install undercloud with external api nw
  command: |
    virt-install --name {{ UNDERCLOUD_NAME }} \
    --disk {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 \
    --vcpus={{ UNDERCLOUD_VCPU }} \
    --ram={{ UNDERCLOUD_RAM }} \
    --network network={{ UNDERCLOUD_DEFAULT_NW }},model=virtio \
    --network network={{ UNDERCLOUD_PROV_NW }},model=virtio \
    --network network={{ UNDERCLOUD_INT_API_NW }},model=virtio \
    --network network={{ UNDERCLOUD_MGMT_NW }},model=virtio \
    --virt-type kvm \
    --cpu host \
    --import \
    --os-variant rhel7 \
    --graphics vnc \
    --serial pty \
    --noautoconsole \
    --console pty,target_type=virtio
  when: UNDERCLOUD_EXTERNAL_API_IP is defined and UNDERCLOUD_MAC is undefined

- name: Install undercloud with static mac and without external api nw
  command: |
    virt-install --name {{ UNDERCLOUD_NAME }} \
    --disk {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 \
    --vcpus={{ UNDERCLOUD_VCPU }} \
    --ram={{ UNDERCLOUD_RAM }} \
    --network network={{ UNDERCLOUD_DEFAULT_NW }},model=virtio \
    --network network={{ UNDERCLOUD_PROV_NW }},model=virtio \
    --network network={{ UNDERCLOUD_INT_API_NW }},model=virtio \
    --mac={{UNDERCLOUD_MAC}} \
    --virt-type kvm \
    --cpu host \
    --import \
    --os-variant rhel7 \
    --graphics vnc \
    --serial pty \
    --noautoconsole \
    --console pty,target_type=virtio
  when: UNDERCLOUD_MAC is defined and UNDERCLOUD_EXTERNAL_API_IP is undefined

- name: Install undercloud with external api nw and static mac
  command: |
    virt-install --name {{ UNDERCLOUD_NAME }} \
    --disk {{ IMAGE_DIRECTORY }}/{{ UNDERCLOUD_NAME }}.qcow2 \
    --vcpus={{ UNDERCLOUD_VCPU }} \
    --ram={{ UNDERCLOUD_RAM }} \
    --network network={{ UNDERCLOUD_DEFAULT_NW }},model=virtio \
    --network network={{ UNDERCLOUD_PROV_NW }},model=virtio \
    --network network={{ UNDERCLOUD_INT_API_NW }},model=virtio \
    --network network={{ UNDERCLOUD_MGMT_NW }},model=virtio \
    --mac={{UNDERCLOUD_MAC}} \
    --virt-type kvm \
    --cpu host \
    --import \
    --os-variant rhel7 \
    --graphics vnc \
    --serial pty \
    --noautoconsole \
    --console pty,target_type=virtio
  when: UNDERCLOUD_EXTERNAL_API_IP is defined and UNDERCLOUD_MAC is defined
